//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class abs_mstr
    {
        public string prrowid { get; set; }
        public string abs_shipfrom { get; set; }
        public string abs_id { get; set; }
        public string abs_par_id { get; set; }
        public string abs_shipto { get; set; }
        public string abs_type { get; set; }
        public string abs_status { get; set; }
        public string abs_timezone { get; set; }
        public Nullable<System.DateTime> abs_shp_date { get; set; }
        public Nullable<int> abs_shp_time { get; set; }
        public Nullable<System.DateTime> abs_arr_date { get; set; }
        public Nullable<int> abs_arr_time { get; set; }
        public Nullable<System.DateTime> abs_crt_date { get; set; }
        public Nullable<int> abs_crt_time { get; set; }
        public Nullable<System.DateTime> abs_apr_date { get; set; }
        public Nullable<int> abs_apr_time { get; set; }
        public string abs_apr_userid { get; set; }
        public Nullable<decimal> abs_gwt { get; set; }
        public Nullable<decimal> abs_nwt { get; set; }
        public Nullable<decimal> abs_vol { get; set; }
        public string abs_wt_um { get; set; }
        public string abs_vol_um { get; set; }
        public string abs_dim_um { get; set; }
        public string abs_fr_class { get; set; }
        public Nullable<decimal> abs_est_fcst { get; set; }
        public Nullable<decimal> abs_act_fcst { get; set; }
        public string abs_fr_curr { get; set; }
        public string abs_doc_data__1 { get; set; }
        public string abs_doc_data__2 { get; set; }
        public string abs_doc_data__3 { get; set; }
        public string abs_doc_data__4 { get; set; }
        public string abs_doc_data__5 { get; set; }
        public string abs_dataset { get; set; }
        public string abs_order { get; set; }
        public string abs_line { get; set; }
        public string abs_inv_nbr { get; set; }
        public string abs_item { get; set; }
        public string abs_lotser { get; set; }
        public string abs_ref { get; set; }
        public Nullable<decimal> abs_qty { get; set; }
        public Nullable<decimal> abs_ship_qty { get; set; }
        public Nullable<decimal> abs_cum_qty { get; set; }
        public string abs_site { get; set; }
        public string abs_loc { get; set; }
        public string abs_cust_ref { get; set; }
        public Nullable<int> abs_cmtindx { get; set; }
        public string abs__chr01 { get; set; }
        public string abs__chr02 { get; set; }
        public string abs__chr03 { get; set; }
        public string abs__chr04 { get; set; }
        public string abs__chr05 { get; set; }
        public string abs__chr06 { get; set; }
        public string abs__chr07 { get; set; }
        public string abs__chr08 { get; set; }
        public string abs__chr09 { get; set; }
        public string abs__chr10 { get; set; }
        public Nullable<decimal> abs__dec01 { get; set; }
        public Nullable<decimal> abs__dec02 { get; set; }
        public Nullable<decimal> abs__dec03 { get; set; }
        public Nullable<decimal> abs__dec04 { get; set; }
        public Nullable<decimal> abs__dec05 { get; set; }
        public Nullable<decimal> abs__dec06 { get; set; }
        public Nullable<decimal> abs__dec07 { get; set; }
        public Nullable<decimal> abs__dec08 { get; set; }
        public Nullable<decimal> abs__dec09 { get; set; }
        public Nullable<decimal> abs__dec10 { get; set; }
        public string abs__qad01 { get; set; }
        public string abs__qad02 { get; set; }
        public string abs__qad03 { get; set; }
        public string abs__qad04 { get; set; }
        public string abs__qad05 { get; set; }
        public string abs__qad06 { get; set; }
        public string abs__qad07 { get; set; }
        public string abs__qad08 { get; set; }
        public string abs__qad09 { get; set; }
        public string abs__qad10 { get; set; }
        public string abs_user1 { get; set; }
        public string abs_user2 { get; set; }
        public string abs_master_id { get; set; }
        public string abs_inv_mov { get; set; }
        public string abs_nr_id { get; set; }
        public string abs_format { get; set; }
        public string abs_cons_ship { get; set; }
        public string abs__qadc01 { get; set; }
        public string abs_lang { get; set; }
        public Nullable<bool> abs_canceled { get; set; }
        public Nullable<decimal> abs__qadd01 { get; set; }
        public Nullable<int> abs_trl_cmtindx { get; set; }
        public Nullable<System.DateTime> abs_eff_date { get; set; }
        public Nullable<System.DateTime> abs_cancel_date { get; set; }
        public string abs_preship_nr_id { get; set; }
        public string abs_preship_id { get; set; }
        public string abs_fa_lot { get; set; }
        public Nullable<System.DateTime> abs_asn_crt_date { get; set; }
        public Nullable<int> abs_asn_crt_time { get; set; }
        public Nullable<int> abs_export_batch { get; set; }
        public Nullable<System.DateTime> abs_export_date { get; set; }
        public Nullable<int> abs_export_time { get; set; }
        public string abs_charge_type { get; set; }
        public Nullable<decimal> abs_price { get; set; }
        public string abs_desc { get; set; }
        public string abs_master_shipfrom { get; set; }
        public string abs_domain { get; set; }
        public Nullable<decimal> oid_abs_mstr { get; set; }
        public Nullable<bool> abs_consigned_return { get; set; }
        public string abs_vend_lot { get; set; }
        public Nullable<decimal> abs_rcpt_qty { get; set; }
        public string abs_routing { get; set; }
        public string abs_bom_code { get; set; }
        public string abs_production_line { get; set; }
        public Nullable<bool> abs_complete { get; set; }
        public Nullable<decimal> abs_scrap_qty { get; set; }
        public Nullable<bool> abs_combined_invoice { get; set; }
        public Nullable<decimal> abs_act_qty { get; set; }
        public Nullable<decimal> abs_bulk_qty { get; set; }
        public Nullable<bool> abs_tax_in { get; set; }
        public string abs_tax_env { get; set; }
        public string abs_tax_usage { get; set; }
        public string abs_taxc { get; set; }
        public Nullable<bool> abs_taxable { get; set; }
        public string abs_acct { get; set; }
        public string abs_sub { get; set; }
        public string abs_cc { get; set; }
        public string abs_proj { get; set; }
        public string abs__qadc02 { get; set; }
        public string abs__qadc03 { get; set; }
        public Nullable<int> abs__qadi01 { get; set; }
        public Nullable<bool> abs__qadl01 { get; set; }
        public Nullable<System.DateTime> abs__qadt01 { get; set; }
        public string abs_ship_type { get; set; }
        public Nullable<decimal> oid_lgdd_det { get; set; }
        public string abs_to_loc { get; set; }
        public string abs_to_site { get; set; }
        public string Pro2SrcPDB { get; set; }
        public Nullable<System.DateTime> pro2created { get; set; }
        public Nullable<System.DateTime> pro2modified { get; set; }
    }
}
