//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrderItem
    {
        public int Id { get; set; }
        public string OrderNbr { get; set; }
        public Nullable<int> LineNbr { get; set; }
        public Nullable<int> Release { get; set; }
        public string Customer { get; set; }
        public string OrigSite { get; set; }
        public string CI { get; set; }
        public string CustomerNbr { get; set; }
        public string PO { get; set; }
        public Nullable<int> ShipTo { get; set; }
        public string Item { get; set; }
        public Nullable<int> TextKey { get; set; }
        public string PackSlipPrintedFlag { get; set; }
        public Nullable<System.DateTime> LastPickList { get; set; }
        public string Origin { get; set; }
        public Nullable<int> Ordered { get; set; }
        public Nullable<int> Packed { get; set; }
        public Nullable<int> Shipped { get; set; }
        public string LRStat { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Warehouse { get; set; }
        public Nullable<System.DateTime> LastShip { get; set; }
        public string ShipSite { get; set; }
        public Nullable<int> SupplUnits { get; set; }
        public string Commodity { get; set; }
        public Nullable<int> ConsNbr { get; set; }
        public string BOLPrintedFlag { get; set; }
    }
}
