//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interchange
    {
        public int Id { get; set; }
        public string SupplierItemNbr { get; set; }
        public string InterchangePartNbr { get; set; }
        public string Revision { get; set; }
        public string Status { get; set; }
    }
}
