//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Id { get; set; }
        public string Item1 { get; set; }
        public string Description { get; set; }
        public string MaterialStatus { get; set; }
        public string StockedFlag { get; set; }
        public string Revision { get; set; }
        public string ReservableFlag { get; set; }
        public string ABCCode { get; set; }
        public string AltItem { get; set; }
        public string BackflushFlag { get; set; }
        public string BackflushLocation { get; set; }
        public string Buyer { get; set; }
        public string PlanningCell { get; set; }
        public Nullable<System.DateTime> LastGenDate { get; set; }
        public string CharFld3 { get; set; }
        public string Commodity { get; set; }
        public string LowLevelCode { get; set; }
        public string DrawingNbr { get; set; }
        public string FamilyCode { get; set; }
        public string LotTrack { get; set; }
        public string Type { get; set; }
        public string OrderMinimum { get; set; }
        public string OrderMultiple { get; set; }
        public string Origin { get; set; }
        public string Source { get; set; }
        public string PlannerCode { get; set; }
        public string ProductionType { get; set; }
        public string ProductCode { get; set; }
        public string PhantomFlag { get; set; }
        public string UnitOfMeasure { get; set; }
        public string UnitCost { get; set; }
        public string CharFld1 { get; set; }
        public string CharFld2 { get; set; }
        public string CharFld4 { get; set; }
        public string WeightUnits { get; set; }
        public string ITAR { get; set; }
        public string HTSCode { get; set; }
        public string ECCN { get; set; }
        public string ECCNLicense { get; set; }
        public string NAFTA { get; set; }
        public string ScheduleB { get; set; }
        public string TestBolt { get; set; }
        public string USOnly { get; set; }
        public string Status { get; set; }
        public string DutyRate { get; set; }
        public string NominalThreadSize { get; set; }
        public string ProductFamily { get; set; }
    }
}
