//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInfo
    {
        public int Id { get; set; }
        public string Item { get; set; }
        public string Description { get; set; }
        public string ThreadSize { get; set; }
        public string ProductFamily { get; set; }
        public string Status { get; set; }
        public bool TestBolt { get; set; }
        public Nullable<int> TextKey { get; set; }
        public Nullable<int> CertTextKey { get; set; }
        public string LogicalField { get; set; }
        public Nullable<int> LastOccurence { get; set; }
        public bool USOnly { get; set; }
    }
}
