//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobInfo
    {
        public int Id { get; set; }
        public string Job { get; set; }
        public int Suffix { get; set; }
        public string Lot { get; set; }
        public string Item { get; set; }
        public string Revision { get; set; }
        public string Certificate { get; set; }
        public string RequireCerts { get; set; }
        public string Completed { get; set; }
        public string ProductFamily { get; set; }
        public string PassedInspection { get; set; }
        public string CertTextKey { get; set; }
        public string ReworkJob { get; set; }
        public string TextKey { get; set; }
        public string Occurrence { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public string NumericFormat { get; set; }
        public string NCMR { get; set; }
        public string Comments { get; set; }
        public string JobInfoEnd { get; set; }
    }
}
