//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LotInfo
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string HeatLotExtension { get; set; }
        public string HeatLotBase { get; set; }
        public string Item { get; set; }
        public string Lot { get; set; }
        public string MaterialSpec { get; set; }
        public Nullable<int> QtyReceived { get; set; }
        public Nullable<int> RefSuffix { get; set; }
        public string RefNbr { get; set; }
        public Nullable<int> RefRelease { get; set; }
        public string Ref { get; set; }
        public string VendorLot { get; set; }
        public string VendorId { get; set; }
        public string MillNbr { get; set; }
    }
}
