//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialTran
    {
        public long TransactionId { get; set; }
        public System.DateTime TransDate { get; set; }
        public string TransType { get; set; }
        public string RefType { get; set; }
        public string RefNbr { get; set; }
        public Nullable<int> RefRelease { get; set; }
        public Nullable<int> RefLineSuffix { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string WorkCtr { get; set; }
        public string Warehouse { get; set; }
        public string Lot { get; set; }
        public string Location { get; set; }
        public string Item { get; set; }
        public string AwaitingEOP { get; set; }
        public string Backflush { get; set; }
        public string MaterialAccount1 { get; set; }
        public string MaterialAccount2 { get; set; }
        public string MaterialAccount3 { get; set; }
        public string MaterialAccount4 { get; set; }
        public string MaterialAccount5 { get; set; }
        public string UserInitials { get; set; }
    }
}
