//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int Id { get; set; }
        public int MaterialId { get; set; }
        public string ControlNbr { get; set; }
        public string VendorNbr { get; set; }
        public string MillNbr { get; set; }
        public string MaterialSpec { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public string Stage { get; set; }
        public string HeatNbr { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> QtyReceived { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string PONbr { get; set; }
        public Nullable<System.DateTime> RecvdDate { get; set; }
    }
}
