//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSP
    {
        public int Id { get; set; }
        public string LotNbr { get; set; }
        public string AttachmentType { get; set; }
        public string FileName { get; set; }
        public Nullable<int> RevNbr { get; set; }
        public Nullable<System.DateTime> RevDate { get; set; }
        public string Stage { get; set; }
    }
}
