//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prh_hist
    {
        public string prrowid { get; set; }
        public string prh_part { get; set; }
        public string prh_nbr { get; set; }
        public Nullable<int> prh_line { get; set; }
        public Nullable<decimal> prh_rcvd { get; set; }
        public Nullable<decimal> prh_pur_cost { get; set; }
        public Nullable<decimal> prh_pur_std { get; set; }
        public Nullable<System.DateTime> prh_rcp_date { get; set; }
        public string prh_vend { get; set; }
        public string prh_receiver { get; set; }
        public string prh_lot { get; set; }
        public string prh_ps_nbr { get; set; }
        public Nullable<decimal> prh_ps_qty { get; set; }
        public Nullable<decimal> prh_bo_qty { get; set; }
        public string prh__qadc02 { get; set; }
        public string prh_xinvoice { get; set; }
        public Nullable<System.DateTime> prh_xinv_dt { get; set; }
        public Nullable<decimal> prh__qadd01 { get; set; }
        public Nullable<decimal> prh_xinv_cst { get; set; }
        public string prh__qadc03 { get; set; }
        public string prh__qadc04 { get; set; }
        public string prh__qadc05 { get; set; }
        public string prh_rev { get; set; }
        public string prh_type { get; set; }
        public Nullable<bool> prh_print { get; set; }
        public Nullable<decimal> prh_lbr_std { get; set; }
        public Nullable<decimal> prh_mtl_std { get; set; }
        public Nullable<decimal> prh_bdn_std { get; set; }
        public Nullable<decimal> prh_sub_std { get; set; }
        public string prh_buyer { get; set; }
        public Nullable<decimal> prh__qad03 { get; set; }
        public string prh__qad02 { get; set; }
        public string prh_shipto { get; set; }
        public Nullable<bool> prh_cst_up { get; set; }
        public string prh_um { get; set; }
        public Nullable<decimal> prh_um_conv { get; set; }
        public string prh_curr { get; set; }
        public Nullable<decimal> prh_ex_rate { get; set; }
        public Nullable<decimal> prh_curr_amt { get; set; }
        public string prh_pay_um { get; set; }
        public Nullable<decimal> prh_pum_conv { get; set; }
        public string prh_user1 { get; set; }
        public string prh_user2 { get; set; }
        public Nullable<decimal> prh_ovh_std { get; set; }
        public string prh_site { get; set; }
        public string prh_ship { get; set; }
        public Nullable<decimal> prh_qty_ord { get; set; }
        public Nullable<System.DateTime> prh_per_date { get; set; }
        public string prh_rcp_type { get; set; }
        public string prh_reason { get; set; }
        public string prh_request { get; set; }
        public string prh_approve { get; set; }
        public Nullable<int> prh__qad04 { get; set; }
        public string prh_tax_at { get; set; }
        public string prh__chr01 { get; set; }
        public string prh__chr02 { get; set; }
        public string prh__chr03 { get; set; }
        public string prh__chr04 { get; set; }
        public string prh__chr05 { get; set; }
        public string prh__chr06 { get; set; }
        public string prh__chr07 { get; set; }
        public string prh__chr08 { get; set; }
        public string prh__chr09 { get; set; }
        public string prh__chr10 { get; set; }
        public Nullable<System.DateTime> prh__dte01 { get; set; }
        public Nullable<System.DateTime> prh__dte02 { get; set; }
        public Nullable<System.DateTime> prh__dte03 { get; set; }
        public Nullable<System.DateTime> prh__dte04 { get; set; }
        public Nullable<System.DateTime> prh__dte05 { get; set; }
        public Nullable<decimal> prh__dec01 { get; set; }
        public Nullable<decimal> prh__dec02 { get; set; }
        public Nullable<decimal> prh__dec03 { get; set; }
        public Nullable<decimal> prh__dec04 { get; set; }
        public Nullable<decimal> prh__dec05 { get; set; }
        public Nullable<bool> prh__log01 { get; set; }
        public Nullable<bool> prh__log02 { get; set; }
        public string prh_rma_type { get; set; }
        public Nullable<bool> prh_fix_rate { get; set; }
        public string prh_po_site { get; set; }
        public Nullable<decimal> prh_cum_req { get; set; }
        public Nullable<decimal> prh_cum_rcvd { get; set; }
        public string prh_fsm_type { get; set; }
        public string prh_bank { get; set; }
        public string prh_curr_rlse_id__1 { get; set; }
        public string prh_curr_rlse_id__2 { get; set; }
        public string prh_curr_rlse_id__3 { get; set; }
        public string prh_element { get; set; }
        public Nullable<bool> prh_fix_pr { get; set; }
        public string prh_tax_usage { get; set; }
        public string prh_tax_env { get; set; }
        public Nullable<decimal> prh_crt_int { get; set; }
        public Nullable<bool> prh_tax_in { get; set; }
        public string prh_taxc { get; set; }
        public string prh_vend_lot { get; set; }
        public Nullable<System.DateTime> prh_ship_date { get; set; }
        public Nullable<int> prh__qadi01 { get; set; }
        public Nullable<decimal> prh_ex_rate2 { get; set; }
        public string prh_ex_ratetype { get; set; }
        public Nullable<int> prh_exru_seq { get; set; }
        public string prh__qadc06 { get; set; }
        public string prh__qadc01 { get; set; }
        public string prh_domain { get; set; }
        public Nullable<decimal> oid_prh_hist { get; set; }
        public Nullable<decimal> oid_lgd_mstr { get; set; }
        public string Pro2SrcPDB { get; set; }
        public Nullable<System.DateTime> pro2created { get; set; }
        public Nullable<System.DateTime> pro2modified { get; set; }
    }
}
