//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public int Id { get; set; }
        public Nullable<int> Cert { get; set; }
        public string Item { get; set; }
        public string Test { get; set; }
        public string Sample1 { get; set; }
        public string ResultCycle { get; set; }
        public string Minimum { get; set; }
        public string Maximum { get; set; }
        public string PassFail { get; set; }
        public string SigDecMin { get; set; }
        public string SigDecMax { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
    }
}
