//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTemplate
    {
        public int Id { get; set; }
        public Nullable<int> Test { get; set; }
        public string Name { get; set; }
        public string UnitOfMeasure { get; set; }
        public string CyclesSamples { get; set; }
        public string Frequency { get; set; }
        public string MaxInstall { get; set; }
        public string MaxValueRequired { get; set; }
        public string SigDecMax { get; set; }
        public string MinBrkway { get; set; }
        public string MinValueRequired { get; set; }
        public string SigDecMin { get; set; }
        public string PassFail { get; set; }
        public string PrintMinMax { get; set; }
        public string Requirements { get; set; }
        public string ResultCycles { get; set; }
        public string SeatLoad { get; set; }
    }
}
