//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSpec
    {
        public int Id { get; set; }
        public string Item { get; set; }
        public string Specification { get; set; }
        public string SpecType { get; set; }
        public string EnteredBy { get; set; }
        public string Job { get; set; }
        public int Suffix { get; set; }
        public string Cert { get; set; }
    }
}
