//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int Id { get; set; }
        public string BoltSpec { get; set; }
        public string CurrentCycle { get; set; }
        public string CurrentSample { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string EnteredBy { get; set; }
        public string Frequency { get; set; }
        public string Description { get; set; }
        public string Item { get; set; }
        public string Job { get; set; }
        public string MasterKey { get; set; }
        public string MaxValueRequired { get; set; }
        public string SigDecMax { get; set; }
        public string MinValueRequired { get; set; }
        public string SigDecMin { get; set; }
        public string NominalThreadSize { get; set; }
        public string PassFail_A { get; set; }
        public string PerformanceSpec { get; set; }
        public string CycleSamples { get; set; }
        public string MaxInstall { get; set; }
        public string MinBrkway { get; set; }
        public string PassFail_B { get; set; }
        public string PrintMinMax { get; set; }
        public string ResultCycles { get; set; }
        public string SeatLoad { get; set; }
        public string Requirements { get; set; }
        public Nullable<int> Cert { get; set; }
        public string Suffix { get; set; }
        public string Template { get; set; }
        public string TestBolt { get; set; }
        public string Name { get; set; }
        public string Test { get; set; }
        public string UnitOfMeasure { get; set; }
        public string Vendor { get; set; }
        public string CertDetail { get; set; }
    }
}
