//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTR_FLS_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_hist
    {
        public string prrowid { get; set; }
        public string tr_part { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
        public Nullable<System.DateTime> tr_per_date { get; set; }
        public string tr_type { get; set; }
        public string tr_loc { get; set; }
        public Nullable<decimal> tr_loc_begin { get; set; }
        public Nullable<decimal> tr_begin_qoh { get; set; }
        public Nullable<decimal> tr_qty_req { get; set; }
        public Nullable<decimal> tr_qty_chg { get; set; }
        public Nullable<decimal> tr_qty_short { get; set; }
        public string tr_um { get; set; }
        public Nullable<System.DateTime> tr_last_date { get; set; }
        public string tr_nbr { get; set; }
        public string tr_so_job { get; set; }
        public string tr_ship_type { get; set; }
        public string tr_addr { get; set; }
        public string tr_rmks { get; set; }
        public string tr_xdr_acct { get; set; }
        public string tr_xcr_acct { get; set; }
        public Nullable<decimal> tr_mtl_std { get; set; }
        public Nullable<decimal> tr_lbr_std { get; set; }
        public Nullable<decimal> tr_bdn_std { get; set; }
        public Nullable<decimal> tr_price { get; set; }
        public Nullable<long> tr_trnbr { get; set; }
        public Nullable<decimal> tr_gl_amt { get; set; }
        public string tr_xdr_cc { get; set; }
        public string tr_xcr_cc { get; set; }
        public string tr_lot { get; set; }
        public Nullable<decimal> tr_sub_std { get; set; }
        public Nullable<System.DateTime> tr_gl_date { get; set; }
        public Nullable<decimal> tr_qty_loc { get; set; }
        public string tr_userid { get; set; }
        public string tr_serial { get; set; }
        public Nullable<System.DateTime> tr_effdate { get; set; }
        public string tr_prod_line { get; set; }
        public string tr_xslspsn1 { get; set; }
        public string tr_xslspsn2 { get; set; }
        public string tr_xcr_proj { get; set; }
        public string tr_xdr_proj { get; set; }
        public Nullable<int> tr_line { get; set; }
        public string tr_user1 { get; set; }
        public string tr_user2 { get; set; }
        public string tr_curr { get; set; }
        public Nullable<decimal> tr_ex_rate { get; set; }
        public string tr_rev { get; set; }
        public Nullable<int> tr_time { get; set; }
        public Nullable<decimal> tr_ovh_std { get; set; }
        public string tr_site { get; set; }
        public string tr_status { get; set; }
        public string tr_grade { get; set; }
        public Nullable<System.DateTime> tr_expire { get; set; }
        public Nullable<decimal> tr_assay { get; set; }
        public string tr_xgl_ref { get; set; }
        public string tr__chr01 { get; set; }
        public string tr__chr02 { get; set; }
        public string tr__chr03 { get; set; }
        public string tr__chr04 { get; set; }
        public string tr__chr05 { get; set; }
        public string tr__chr06 { get; set; }
        public string tr__chr07 { get; set; }
        public string tr__chr08 { get; set; }
        public string tr__chr09 { get; set; }
        public string tr__chr10 { get; set; }
        public string tr__chr11 { get; set; }
        public string tr__chr12 { get; set; }
        public string tr__chr13 { get; set; }
        public string tr__chr14 { get; set; }
        public string tr__chr15 { get; set; }
        public Nullable<System.DateTime> tr__dte01 { get; set; }
        public Nullable<System.DateTime> tr__dte02 { get; set; }
        public Nullable<System.DateTime> tr__dte03 { get; set; }
        public Nullable<System.DateTime> tr__dte04 { get; set; }
        public Nullable<System.DateTime> tr__dte05 { get; set; }
        public Nullable<decimal> tr__dec01 { get; set; }
        public Nullable<decimal> tr__dec02 { get; set; }
        public Nullable<decimal> tr__dec03 { get; set; }
        public Nullable<decimal> tr__dec04 { get; set; }
        public Nullable<decimal> tr__dec05 { get; set; }
        public Nullable<bool> tr__log01 { get; set; }
        public Nullable<bool> tr__log02 { get; set; }
        public string tr_ref { get; set; }
        public Nullable<int> tr_msg { get; set; }
        public string tr_program { get; set; }
        public Nullable<int> tr_ord_rev { get; set; }
        public string tr_ref_site { get; set; }
        public string tr_rsn_code { get; set; }
        public string tr_vend_lot { get; set; }
        public Nullable<System.DateTime> tr_vend_date { get; set; }
        public string tr_daycode { get; set; }
        public string tr_for { get; set; }
        public string tr_slspsn__1 { get; set; }
        public string tr_slspsn__2 { get; set; }
        public string tr_slspsn__3 { get; set; }
        public string tr_slspsn__4 { get; set; }
        public string tr_fsm_type { get; set; }
        public Nullable<bool> tr_upd_isb { get; set; }
        public Nullable<bool> tr_auto_install { get; set; }
        public string tr_ca_int_type { get; set; }
        public Nullable<decimal> tr_covered_amt { get; set; }
        public string tr_fcg_code { get; set; }
        public string tr_batch { get; set; }
        public string tr_fsc_code { get; set; }
        public string tr_sa_nbr { get; set; }
        public string tr_sv_code { get; set; }
        public string tr_eng_area { get; set; }
        public string tr_sys_prod { get; set; }
        public string tr_svc_type { get; set; }
        public Nullable<System.DateTime> tr_ca_opn_date { get; set; }
        public Nullable<decimal> tr_cprice { get; set; }
        public string tr_eng_code { get; set; }
        public Nullable<int> tr_wod_op { get; set; }
        public string tr_enduser { get; set; }
        public string tr_ship_inv_mov { get; set; }
        public Nullable<System.DateTime> tr_ship_date { get; set; }
        public string tr_ship_id { get; set; }
        public Nullable<decimal> tr_ex_rate2 { get; set; }
        public string tr_ex_ratetype { get; set; }
        public Nullable<int> tr_exru_seq { get; set; }
        public Nullable<System.DateTime> tr_promise_date { get; set; }
        public Nullable<int> tr_fldchg_cmtindx { get; set; }
        public string tr_domain { get; set; }
        public Nullable<decimal> oid_tr_hist { get; set; }
        public Nullable<decimal> tr_qty_cn_adj { get; set; }
        public string tr_doc_id { get; set; }
        public Nullable<decimal> oid_lgd_mstr { get; set; }
        public Nullable<System.DateTime> tr_wo_due_date { get; set; }
        public string tr_wo_line { get; set; }
        public Nullable<decimal> tr_wo_qty_comp { get; set; }
        public Nullable<decimal> tr_wo_qty_ord { get; set; }
        public Nullable<decimal> tr_wo_yield_pct { get; set; }
        public Nullable<decimal> tr_intercompanyref { get; set; }
        public Nullable<long> tr_pc_sequence { get; set; }
        public Nullable<decimal> tr_gl_amt_sc { get; set; }
        public string Pro2SrcPDB { get; set; }
        public Nullable<System.DateTime> pro2created { get; set; }
        public Nullable<System.DateTime> pro2modified { get; set; }
    }
}
